import { range, uniq } from 'lodash';
import { randomBotStrategy, smartBotStrategy } from './bot-strategy';
import { isAllowed, moves, type Board } from './gameplay';
import { botNextMoveArgs, makeCtx, moveValidator } from 'test-utils';

const table = (size: number, previousMove: number | null = null, removed: number[] = []): Board => ({
  numbersOnTable: range(1, size + 1).map(n => !removed.includes(n)),
  previousMove
});

const isRemovalAllowed = moveValidator(moves.removeNumber);

const numberNamed = (board: Board): number =>
  botNextMoveArgs(smartBotStrategy({ board, ctx: makeCtx() }))[0];

const namedOver = (board: Board, draws = 40): number[] =>
  uniq(range(draws).map(() => numberNamed(board))).sort((a, b) => a - b);

// This bot decides nothing itself: it looks the position up in the book
// generated by scripts/pre-generate-ai-moves/remove-divisor-multiple.py, keyed
// by the numbers still on the table and the opponent's last move. So the spec
// asks whether the lookup finds the right entry, not whether the book is right.
describe('smartBotStrategy', () => {
  it.each([7, 9])('opens a table of %i by taking 5 or 7, and nothing else', size => {
    expect(namedOver(table(size))).toEqual([5, 7]);
  });

  it('has no winning opening on a table of 6, so every number stays on the table', () => {
    // The generator writes out every legal move when the position is lost,
    // which is why a losing opening looks like a wide-open choice.
    expect(namedOver(table(6), 80)).toEqual([1, 2, 3, 4, 5, 6]);
  });

  it.each([
    [6, 3],
    [5, 1]
  ])('answers the opponent\'s %i on a table of 6 with the only winning reply, %i',
    (opponentTook, reply) => {
      expect(namedOver(table(6, opponentTook, [opponentTook]))).toEqual([reply]);
    });

  it('falls back to a legal number on a table size the book does not cover', () => {
    // `generateStartBoard` only deals 6..15, so this arm is unreachable in
    // play; it is what stops an unknown size from being a crash.
    const board = table(5);
    for (const named of range(20).map(() => numberNamed(board))) {
      expect(isRemovalAllowed(board, named)).toBe(true);
    }
  });

  it('only ever names a number that is still on the table and divides or multiplies the last', () => {
    const boards = range(6, 10).flatMap(size =>
      [table(size), ...range(1, size + 1).map(n => table(size, n, [n]))]
        .filter(board => range(1, size + 1).some(n => isAllowed(board, n))));

    const illegal = boards.flatMap(board =>
      range(10)
        .map(() => numberNamed(board))
        .filter(named => !isRemovalAllowed(board, named))
        .map(named => `${board.numbersOnTable.length}/${board.previousMove} -> ${named}`));

    expect(uniq(illegal)).toEqual([]);
  });
});

describe('randomBotStrategy', () => {
  it('draws only from the legal numbers', () => {
    const board = table(8, 4, [4]);
    const illegal = range(40)
      .map(() => botNextMoveArgs(randomBotStrategy({ board, ctx: makeCtx() }))[0])
      .filter(named => !isRemovalAllowed(board, named));

    expect(illegal).toEqual([]);
  });
});
