name: deploy
on:
  push:
    branches: [production]

jobs:
  test:
    runs-on: ubuntu-20.04
    container:
      image: node:16.0.0
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm t
      - run: npm build
      - run: cd dist
      - run: git init
      - run: git add -A
      - run: git commit -m 'deploy'
      - run: git push -f git@github.com:a-gondolkodas-orome/durer-jatekok.git master:gh-pages
