name: deploy
on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    container:
      image: node:16.0.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: test and build
        run: |
          npm ci
          npm run test
          npm run build
      - name: Install rsync
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
