name: test
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: pr-test-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-24.04
    container:
      image: node:24.11.1
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Cache npm downloads
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: test and build
        run: |
          npm ci
          npm run test
          npm run build
