name: test
on:
  push:
    branches-ignore:
      - production
      - gh-pages

jobs:
  test:
    runs-on: ubuntu-20.04
    container:
      image: node:16.13.1
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm t
